{"name": "test_issues_create_user_033", "status": "failed", "statusDetails": {"message": "AssertionError: \u001b[31mFAILURE: \u001b[0mcheck Вальдемар == Ne ny eto odnoznachno: Ошибка! Переданное значение 'Вальдемар' не совпадает с зарегистрированным 'Ne ny eto odnoznachno'\n\u001b[31mtest_users.py\u001b[0m:383 in test_issues_create_user_033() -> api.run_tests()\n\u001b[31missues_create_user_033.py\u001b[0m:19 in run_tests() -> self.user_validation(user_data)\n\u001b[31musers_methods.py\u001b[0m:51 in user_validation() -> check.equal(test_data[key], response_data[key], msg=f\"Ошибка! Переданное значение \"\n\n\u001b[31mFAILURE: \u001b[0mcheck Евлампиевич == BAGGGGGGGG: Ошибка! Переданное значение 'Евлампиевич' не совпадает с зарегистрированным 'BAGGGGGGGG'\n------------------------------------------------------------\nFailed Checks: 2", "trace": "\u001b[31mFAILURE: \u001b[0mcheck Вальдемар == Ne ny eto odnoznachno: Ошибка! Переданное значение 'Вальдемар' не совпадает с зарегистрированным 'Ne ny eto odnoznachno'\n\u001b[31mtest_users.py\u001b[0m:383 in test_issues_create_user_033() -> api.run_tests()\n\u001b[31missues_create_user_033.py\u001b[0m:19 in run_tests() -> self.user_validation(user_data)\n\u001b[31musers_methods.py\u001b[0m:51 in user_validation() -> check.equal(test_data[key], response_data[key], msg=f\"Ошибка! Переданное значение \"\n\n\u001b[31mFAILURE: \u001b[0mcheck Евлампиевич == BAGGGGGGGG: Ошибка! Переданное значение 'Евлампиевич' не совпадает с зарегистрированным 'BAGGGGGGGG'\n------------------------------------------------------------\nFailed Checks: 2"}, "description": "\n    Это специальный тест, где мы получим заведомо не верный ответ от сервера.\n    Зарегистрировать нового пользователя (делаем громоздко внутри теста, не используем фикстуру, т.к. тут уникальный\n    URL, и не хочется из-за него заводить новые фикстуры. Это, все-таки, специальная демонстрация возможных ошибок\n\n    Ожидаемый результат:\n        Запрос успешно отправлен;\n        Статус-код 201;\n        Время ответа сервера - не превышает 500ms;\n        Схема JSON-ответа соответствует Требованиям;\n        Response header \"Content-Type\" - \"application/json\"\n        Response header \"Connection\" - \"keep-alive\"\n        Соединение безопасное, порт 443\n        Новая запись JSON ответа соответствует тому, что мы отправляли при регистрации + содержит Id созданного юзера\n\n    Полученный результат: все данные пользователя не совпадают\n    ", "start": 1721415265308, "stop": 1721415265404, "uuid": "eb3518ea-d3e8-4bac-9b1c-7336f9a23fb5", "historyId": "320239184f51c8cab8021f7d8fa592cc", "testCaseId": "320239184f51c8cab8021f7d8fa592cc", "fullName": "tests.users.test_users#test_issues_create_user_033", "labels": [{"name": "tag", "value": "users"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "DESKTOP-55MLA3F"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}