{"name": "test_get_created_user_by_incorrect_id_025", "status": "passed", "description": "\n    Получить данные пользователя по не корректному user_id\n\n    Ожидаемый результат:\n        Статус-код 404;\n        Время ответа сервера - не превышает 500ms;\n        Схема JSON-ответа соответствует Требованиям;\n        Response header \"Content-Type\": \"application/json\"\n        Response header \"Connection\": \"keep-alive\"\n        В JSON - присутствует ключ detail, значением является описание ошибки\n        В тексте ошибки указан отправленный нами \"user_id\"\n    ", "start": 1721415264450, "stop": 1721415264522, "uuid": "489e8612-4011-4725-bede-50d5504379b9", "historyId": "5adeac665b4dc549e23c4f22d4243df4", "testCaseId": "5adeac665b4dc549e23c4f22d4243df4", "fullName": "tests.users.test_users#test_get_created_user_by_incorrect_id_025", "labels": [{"name": "tag", "value": "users"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "DESKTOP-55MLA3F"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}